In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding

In [2]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [4]:
tokenizer.fit_on_texts(docs)

In [5]:
len(tokenizer.word_index)

17

In [6]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [7]:
from tensorflow.keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [8]:
vocab_size = len(tokenizer.word_index) + 1
vocab_size

18

In [9]:
model = Sequential()
model.add(Embedding(vocab_size, output_dim=2, input_length=5))
model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.compile('adam','accuracy')

In [11]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 595ms/step
[[[-0.03918269  0.00320504]
  [-0.00102242 -0.03137334]
  [-0.02523062  0.03327568]
  [-0.02523062  0.03327568]
  [-0.02523062  0.03327568]]

 [[-0.00102242 -0.03137334]
  [-0.00102242 -0.03137334]
  [-0.02523062  0.03327568]
  [-0.02523062  0.03327568]
  [-0.02523062  0.03327568]]

 [[ 0.04500235  0.00087424]
  [ 0.04500235  0.00087424]
  [-0.00530623  0.04383219]
  [-0.02523062  0.03327568]
  [-0.02523062  0.03327568]]

 [[-0.01134658 -0.03959275]
  [-0.00100387  0.00758575]
  [-0.01134658 -0.03959275]
  [-0.00102242 -0.03137334]
  [-0.01134658 -0.03959275]]

 [[-0.04809786  0.00620453]
  [-0.0231897  -0.0493134 ]
  [-0.0263561  -0.01853251]
  [ 0.01421747 -0.03745464]
  [-0.02523062  0.03327568]]

 [[ 0.04188689 -0.03511969]
  [ 0.04188689 -0.03511969]
  [-0.02523062  0.03327568]
  [-0.02523062  0.03327568]
  [-0.02523062  0.03327568]]

 [[ 0.01204001  0.0312175 ]
  [ 0.01204001  0.0312175 ]
  [-0.02523062  0.03327568]
  [-0.02523062  0.0332756

# Real Example

In [12]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten, Embedding,SimpleRNN

In [13]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [14]:
X_train = pad_sequences(X_train, padding = 'post')
X_test = pad_sequences(X_test, padding = 'post')

In [15]:
X_train.shape

(25000, 2494)

In [16]:
import numpy as np
vocab_size = np.max(X_train) + 1
vocab_size

88587

In [17]:
model = Sequential()
model.add(Embedding(vocab_size, 2, input_length=2494))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation  = 'sigmoid'))

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn (SimpleRNN)               │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.compile(optimizer = "adam",
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

In [ ]:
history = model.fit(X_train, y_train,
                    epochs=5,
                    batch_size=32,
                    validation_data=(X_test, y_test))